<!doctype html>
<html>
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>

    <title>${title}</title>
    <style media="screen,print" type="text/css">
        @page {
            size: A4;
            margin-left: 0;
            margin-right: 0;
            margin-top: 13.5mm;
            margin-bottom: 10.5mm;
        }

        p {
            margin: 0;
            padding: 0;
        }

        em {
            font-size: 12px;
            display: block;
            margin-left: 3mm;
        }

        typtext {
            font-size: 12px;
            display: block;
            height: 20mm;
            max-width: 90mm;
            overflow: hidden;
            margin-left: auto;
            margin-right: auto;
        }

        emcentered {
            text-align: center;
            margin-left: auto;
            margin-right: auto;
            font-size: 10px;
            margin-top: 5px;
            display: block;
        }

        rok {
            text-align: center;
            margin-left: auto;
            margin-right: auto;
            font-size: 48px;
            margin-bottom: 3px;
            margin-top: -8px;
            display: block;
        }

        zahlavi {
            text-align: left;
            margin-left: auto;
            margin-right: auto;
            font-size: 16px;
            margin-bottom: 5px;
        }



        body {
            margin: 0px;
            padding: 0px;
            font-family: Verdana, Arial;
        }

        #wrapper {
            width: 194mm;
            margin-left: auto;
            margin-right: auto;
            border-top: 0;
        }

        #content {
            padding: 0 0px 0 0px;
        }



        .clr {
            clear: both;
        }


    </style>

</head>

<body>



